# Nifty Midcap 100 Constituent Ticker List
MIDCAP_100 = [
    "RECL.NS", "PFC.NS", "SJVN.NS", "NHPC.NS", "BHEL.NS", "IRCON.NS", "BEL.NS", "HAL.NS", "BDL.NS",
    "MAZDOCK.NS", "GRSE.NS", "OIL.NS", "HPCL.NS", "SAIL.NS", "NMDC.NS", "NATIONALUM.NS", "HINDCOPPER.NS", 
    "TRENT.NS", "TATAMOTORS.NS", "POLYCAB.NS", "GMRINFRA.NS", "HUDCO.NS", "IRFC.NS", "CANBK.NS", "PNB.NS", 
    "UNIONBANK.NS", "BOB.NS", "INDIANB.NS", "UCOBANK.NS", "FEDERALBANK.NS", "IDFCFIRSTB.NS", "AUBANK.NS", 
    "BANDHANBNK.NS", "YESBANK.NS", "LUPIN.NS", "AUROPHARMA.NS", "BIOCON.NS", "GLENMARK.NS", "LAURUSLABS.NS",
    "ASHOKLEY.NS", "BALKRISIND.NS", "MRF.NS", "APLLTD.NS", "COFORGE.NS", "PERSISTENT.NS", "MPHASIS.NS", 
    "KPITTECH.NS", "LTTS.NS", "TATACOMM.NS", "JINDALSTEL.NS", "VOLTAS.NS", "CUMMINSIND.NS", "AIAENG.NS", 
    "BHARATFORG.NS", "HINDPETRO.NS", "PETRONET.NS", "IGL.NS", "MGL.NS", "GUJGASLTD.NS", "ABFRL.NS", 
    "JUBILANT.NS", "DEVYANI.NS", "PAGEIND.NS", "BATAINDIA.NS", "RELAXO.NS", "METROPOLIS.NS", "LALPATHLAB.NS", 
    "IPCALAB.NS", "ZYDUSLIFE.NS", "DIVISLAB.NS", "GLAXO.NS", "SANOFI.NS", "ALKEM.NS", "ABBOTINDIA.NS", 
    "PFIZER.NS", "SYNGENE.NS", "ZEEL.NS", "SUNTV.NS", "DISHTV.NS", "PVRINOX.NS", "NAUKRI.NS", "ZOMATO.NS", 
    "NYKAA.NS", "PAYTM.NS", "POLICYBZR.NS", "CARBORUNDT.NS", "CHOLAFIN.NS", "SHRIRAMFIN.NS", "MUTHOOTFIN.NS", 
    "M&MFIN.NS", "LICHSGFIN.NS", "AAVAS.NS", "TATAELXSI.NS", "LTIM.NS", "PEL.NS", "GODREJPROP.NS", "OBEROIRLTY.NS",
    "PHOENIXLTD.NS", "PRESTIGE.NS", "DLF.NS"
]

# Nifty Smallcap 100 Constituent Ticker List
SMALLCAP_100 = [
    "SUZLON.NS", "NBCC.NS", "HFCL.NS", "JWL.NS", "GIPCL.NS", "CESC.NS", "JSWENERGY.NS", "TATAPOWER.NS", 
    "MAHABANK.NS", "IOB.NS", "CENTRALBK.NS", "PSB.NS", "J&KBANK.NS", "SOUTHBANK.NS", "KARURVYSYA.NS", 
    "CUB.NS", "DCBBANK.NS", "RBLBANK.NS", "KFINTECH.NS", "PRUDENT.NS", "UTIAMC.NS", "NIPPONLIFE.NS", 
    "HDFCAMC.NS", "ABSLAMC.NS", "EASEMYTRIP.NS", "YATRA.NS", "MAPMYINDIA.NS", "TEJASNET.NS", "ZENSARTECH.NS", 
    "CYIENT.NS", "SONATSOFTW.NS", "BSOFT.NS", "INTELLECT.NS", "NEWGEN.NS", "MASTEK.NS", "RATEGAIN.NS", 
    "CEINFO.NS", "ELECON.NS", "ACTIONCONST.NS", "TRITURBINE.NS", "ISGEC.NS", "KEC.NS", "KALPATARUP.NS", 
    "ENGINERSIN.NS", "TECHNOE.NS", "GEPIL.NS", "BGRENERGY.NS", "NCC.NS", "ITDCEM.NS", "JKIL.NS", 
    "PNCINFRA.NS", "HGINFRA.NS", "DILIPBUILD.NS", "KNRCON.NS", "PSPPROJECT.NS", "ASHOKA.NS", "GPIL.NS", 
    "WELCORP.NS", "JSL.NS", "JINDALSAW.NS", "MAHSEAMLES.NS", "APLAPOLLO.NS", "GMMPFAUDLR.NS", "HEG.NS", 
    "GRAPHITE.NS", "KEI.NS", "RRKABEL.NS", "FINCABLES.NS", "HAVELLS.NS", "VGUARD.NS", "ORIENTELEC.NS", 
    "CROMPTON.NS", "BAJAJELEC.NS", "EIDPARRY.NS", "BALRAMCHIN.NS", "TRIVENI.NS", "SHREECEM.NS", "JKCEMENT.NS", 
    "RAMCOCEM.NS", "BIRLACORPN.NS", "HEIDELBERG.NS", "INDIACEM.NS", "ORIENTCEM.NS", "BSE.NS", "CDSL.NS", 
    "MCX.NS", "IEX.NS", "ANGELONE.NS", "TATACHEM.NS", "DEEPAKNTR.NS", "SRF.NS", "GFL.NS", "GUJALKALI.NS", 
    "GNFC.NS", "GSFC.NS", "FACT.NS", "RCF.NS", "NFL.NS"
]
